// Generates sw.js after the build: precaches every file of the static output
// so the app opens and works with no network. The cache name is a hash of all
// file contents, so each new build is picked up as an update.
// Usage: node scripts/build-sw.mjs [output-dir]   (default: out)
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = path.resolve(process.argv[2] ?? "out");
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

function walk(dir) {
  return readdirSync(dir).flatMap((name) => {
    const full = path.join(dir, name);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(OUT)
  .map((f) => path.relative(OUT, f).split(path.sep).join("/"))
  // _headers / _redirects are host config, not served files
  .filter((f) => f !== "sw.js" && !f.endsWith(".map") && !/^_(headers|redirects)$/.test(f))
  .sort();

const hash = createHash("sha256");
for (const f of files) hash.update(f).update(readFileSync(path.join(OUT, f)));
const version = hash.digest("hex").slice(0, 12);

const urls = files.map((f) => `${basePath}/${f}`);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = "fruit-${version}";
const BASE = ${JSON.stringify(basePath)};
const PRECACHE = ${JSON.stringify(urls)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("fruit-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// The page asks for this when the user taps "به‌روزرسانی".
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});

// "/day/" and "/day" are both served by "/day/index.html".
function pageFor(url) {
  const p = url.pathname.endsWith("/") ? url.pathname : url.pathname + "/";
  return p + "index.html";
}

self.addEventListener("fetch", (event) => {
  const { request } = event;
  const url = new URL(request.url);
  if (request.method !== "GET" || url.origin !== self.location.origin) return;

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      if (request.mode === "navigate") {
        const page = await cache.match(pageFor(url));
        return page ?? (await cache.match(BASE + "/index.html")) ?? fetch(request);
      }
      // Cache first (files are content-hashed or versioned by CACHE), network as fallback.
      return (await cache.match(request, { ignoreSearch: true })) ?? fetch(request);
    })(),
  );
});
`;

writeFileSync(path.join(OUT, "sw.js"), sw);
console.log(`sw.js: ${files.length} files precached, cache fruit-${version}`);
